create table if not exists doctor(
    id int generated by default as identity primary key,
    lastName varchar(200) not null,
    firstName varchar(200) not null,
    patronymic varchar(200),
    birthday date not null,
    patient_id_array int[] not null
);

create table if not exists patient(
    id int generated by default as identity primary key,
    lastName varchar(200) not null,
    firstName varchar(200) not null,
    patronymic varchar(200),
    birthday date not null,
    job varchar(300) not null,
    doctor_id integer not null,
    foreign key (doctor_id) references doctor (id)
);
