create table if not exists clinic(
id int4 generated by default as identity primary key,
name_clinic varchar(200) not null,
address varchar(200) not null,
type_clinic varchar(100) not null,
doctors int4[],
patients int4[]
);

create table if not exists doctor(
id int4 generated by default as identity primary key,
lastName varchar(200) not null,
firstName varchar(200) not null,
patronymic varchar(200),
specialization varchar(300) not null,
clinic_id int4,
patients int4[]
);

create table if not exists patient(
id int4 generated by default as identity primary key,
lastName varchar(200) not null,
firstName varchar(200) not null,
patronymic varchar(200),
job varchar(300) not null,
doctors int4[],
clinics int4[]
);
